### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by Quintin82** [Pima-GAM150/Quintin-Cody#1]
im having trouble with the speed of my movement but when i change it it does not change the speed of the object like it should here is my code

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class movement : MonoBehaviour {
public float speed = 1f;
public float rotationspeed = 1f;
// Use this for initialization
void Start () {

}

// Update is called once per frame
void Update () {
    transform.Translate(Input.GetAxis("Horizontal")*Time.deltaTime, 0f, 0f);
    transform.Translate(0f,Input.GetAxis("Vertical") * Time.deltaTime,0f);
}

}

**Comment by andrew6180** [comment]
You're assigning values to speed and rotationspeed but never actually using them. You might try doing 
```
    void Update()
    {
        // get our axis values
        var horizontal = Input.GetAxis("Horizontal") * Time.deltaTime;
        var vertical = Input.GetAxis("Vertical") * Time.deltaTime;
        // create a movement vector
        Vector3 movement = new Vector3(horizontal, vertical, 0f);
        // this is optional but it would prevent diagonal movement being faster than pure forward or horizontal.
        movement.Normalize();
        // apply our speed
        movement *= speed;
        // translate in our new direction
        transform.Translate(movement);
    }
```
